CREATE TABLE Usuario (
	id SERIAL NOT NULL,
	email VARCHAR(60) NOT NULL UNIQUE,
	nome VARCHAR(60) NOT NULL,
	senha VARCHAR(20)NOT NULL,		
	foto VARCHAR (255),
	tipo VARCHAR (20) NOT NULL,
	matricula VARCHAR (20) NOT NULL,
	PRIMARY KEY(id)
);